### PR TITLE
Add host envs

### PR DESCRIPTION
**Pull request by aborilov**
Add MYSQL_ENV_MYSQL_HOST and POSTGRES_ENV_POSTGRES_HOST
Set this env to use redmine with database not linked to this container.

### CODE REVIEW

**Comment by Pimo** [comment]
+1

**Comment by guenter** [comment]
Would love to see this committed as well

**Comment by lupa18** [comment]
+1

**Comment by tianon** [comment]
I like where this is headed (since `--link` is slowly phasing out thanks to Docker networks), but I think it's going to need to be a bit more complicated to ensure it's easy for folks to actually use.  Here's what I've got in mind: (although caveat that the final decision is going to be up to @yosifkit)

```bash
if [ ! -f './config/database.yml' ]; then
	if [ "$MYSQL_PORT_3306_TCP" ]; then
		: "${REDMINE_DB_MYSQL:=mysql}"
	elif [ "$POSTGRES_PORT_5432_TCP" ]; then
		: "${REDMINE_DB_POSTGRES:=postgres}"
	fi
	if [ "$REDMINE_DB_MYSQL" ]; then
		adapter='mysql2'
		host="$REDMINE_DB_MYSQL"
		: "${REDMINE_DB_PORT:=3306}"
		: "${REDMINE_DB_USERNAME:=${MYSQL_ENV_MYSQL_USER:-root}}"
		: "${REDMINE_DB_PASSWORD:=${MYSQL_ENV_MYSQL_PASSWORD:-$MYSQL_ENV_MYSQL_ROOT_PASSWORD}}"
		: "${REDMINE_DB_DATABASE:=${MYSQL_ENV_MYSQL_DATABASE:-${MYSQL_ENV_MYSQL_USER:-redmine}}}"
		: "${REDMINE_DB_ENCODING:=}"
	elif [ "$REDMINE_DB_POSTGRES" ]; then
		adapter='postgres'
		host="$REDMINE_DB_POSTGRES"
		: "${REDMINE_DB_PORT:=5432}"
		: "${REDMINE_DB_USERNAME:=${POSTGRES_ENV_POSTGRES_USER:-postgres}}"
		: "${REDMINE_DB_PASSWORD:=${POSTGRES_ENV_POSTGRES_PASSWORD}}"
		: "${REDMINE_DB_DATABASE:=${POSTGRES_ENV_POSTGRES_DB:-$REDMINE_DB_USERNAME}}"
		: "${REDMINE_DB_ENCODING:=utf8}"
	else
		adapter='sqlite3'
		host='localhost'
		: "${REDMINE_DB_PORT:=}"
		: "${REDMINE_DB_USERNAME:=redmine}"
		: "${REDMINE_DB_PASSWORD:=}"
		: "${REDMINE_DB_DATABASE:=sqlite/redmine.db}"
		: "${REDMINE_DB_ENCODING:=utf8}"
	fi

	cat > './config/database.yml' <<-YML
		$RAILS_ENV:
		  adapter: $adapter
		  host: $host
		  port: $REDMINE_DB_PORT
		  username: $REDMINE_DB_USERNAME
		  password: $REDMINE_DB_PASSWORD
		  database: $REDMINE_DB_DATABASE
		  encoding: $REDMINE_DB_ENCODING
	YML
fi
```

**Pull request closed without merging**
