### PR TITLE
Add passenger image for redmine 5.0.4

### PR DESCRIPTION
**Pull request by apankratiev-syberry**

### CODE REVIEW

**Comment by yosifkit** [comment]
This was omitted on purpose when `5.0.0` was addded in https://github.com/docker-library/redmine/pull/261:

> Given this is a major release, we're finally removing the passenger variant (it hasn't been well supported for quite some time).

**Comment by lmoellendorf** [comment]
I used the passenger image because it was the only way I found to use HTTPS:

- https://github.com/docker-library/redmine/issues/207
- https://github.com/docker-library/redmine/issues/4#issuecomment-149335151

Is there any documentation on how to enable HTTPS without passenger?

**Comment by kayrus** [comment]
Any updates on the passenger support for redmine 5?

**Comment by tianon** [comment]
Sorry!  We really appreciate the contribution, but we did drop passenger support intentionally. :heart:

**Pull request closed without merging**
