### PR TITLE
Add support for SMTP configuration

### PR DESCRIPTION
**Pull request by sandratatarevicova**
This PR adds support for SMTP configuration using environment variables. Supported environment variables are:

- `REDMINE_SMTP_DELIVERY_METHOD`
- `REDMINE_SMTP_ADDRESS`
- `REDMINE_SMTP_PORT`
- `REDMINE_SMTP_DOMAIN`
- `REDMINE_SMTP_USER_NAME`
- `REDMINE_SMTP_PASSWORD`
- `REDMINE_SMTP_AUTHENTICATION`
- `REDMINE_SMTP_ENABLE_STARTTLS_AUTO`
- `REDMINE_SMTP_OPENSSL_VERIFY_MODE`
- `REDMINE_SMTP_SSL`

If `REDMINE_SMTP_ADDRESS` is set a configuration file `config/configuration.yml` is generated based on the environment variable(s) if it does not exist.

If/after this PR is merged, [README in the documentation](https://github.com/docker-library/docs/blob/master/redmine/README.md) should be updated. I will create a PR if this is approved :-)

### CODE REVIEW

**Comment by tianon** [comment]
I'm hesitant on this because it is a further divergence from what upstream officially provides out-of-the-box -- IMO, this is better suited to users doing a bind-mount, `docker config`, Kubernetes `ConfigMap`, etc to provide `config/configuration.yml` directly.

**Comment by sandratatarevicova** [comment]
I understand, but I think that the configuration should be consistent. With the current image, you can configure all common options except the SMTP settings using environment variables, but SMTP settings have to be configured in file. When I was testing the image and I wanted to configure the SMTP settings I expected it would be configurable using environment variables the same way as other settings and it seems some other users were expecting it as well (#20).

**Comment by tianon** [comment]
Looking at https://github.com/redmine/redmine/blob/4.1.0/config/configuration.yml.example, there is more than just SMTP missing in the environment variables we support, which is just looking at `config/configuration.yml` (not taking into account things that are considered "configurable" but require changing other files under `config/` such as `additional_environment.rb`).

To put this another way -- we regret deviating from a standard Redmine install with the environment variables we already support, and would much rather see Redmine upstream support environment variable-based configuration directly (and thus deprecate the munging we currently do in favor of just scraping the upstream-supported Redmine configuration for which database adapter to ensure is installed, for example).

**Comment by sandratatarevicova** [comment]
> Looking at https://github.com/redmine/redmine/blob/4.1.0/config/configuration.yml.example, there is more than just SMTP missing in the environment variables we support, which is just looking at config/configuration.yml (not taking into account things that are considered "configurable" but require changing other files under config/ such as additional_environment.rb).

That's true, but most of the users will probably not need to change these variables. For the minimal setup, you need to configure the database connection and SMTP settings. And I think it would be nice if it was configurable in a consistent way.

> would much rather see Redmine upstream support environment variable-based configuration directly

I completely agree. Is there some ticket for it on redmine.org? I did not find it, but I can create it.

**Comment by tianon** [comment]
> I completely agree. Is there some ticket for it on redmine.org? I did not find it, but I can create it.

I don't think there is, although it's probably worth noting there's *some* minor precedence here with `REDMINE_LANG` (https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-7-Database-default-data-set). :smile:

**Comment by tianon** [comment]
Closing since this isn't something we want to support/maintain (as discussed above).  If someone ends up opening a feature request with upstream to support more environment-variable-based configuration parameters, please link it back here!  (I would *love* to deprecate most of our entrypoint script.)

Thanks for the contribution and discussion :heart:

**Comment by yuri-karpovich** [comment]
Such a nice feature :( I just want to create docker-compose and start a service from it. I don't want to pre-configure config.yml, I just want to setup all my basic settings via ENV (as it works for almost all services

**Comment by pini-gh** [comment]
How about just adding something like this snippet to the entrypoint script?
```bash
config_vars=$(env | sed -En '/^(REDMINE_CONFIGURATION_[^=]+)=.*$/{s//\1/;p}')
if [ -n "$config_vars" ]; then
  config_json="{\"default\":{"
  for var in $config_vars; do
    config_json+="${!var},"
  done
  config_json="${config_json:0:-1}}}"
  ruby -ryaml -rjson -e "puts JSON.parse(STDIN.read).to_yaml.sub(/^([ ]*[^ ]+): _3A_([^ ]+)/, '\1: :\2').sub(/ '(true|false)'$/, ' \1')" <<<"$config_json" | tail -n +2 >config/configuration.yml
fi
```
Then it would be possible to set up a whole custom `configuration.yml` file just from environment variables holding json snippets, provided these variables' names start with `REDMINE_CONFIGURATION_`.

For example:
```bash
REDMINE_CONFIGURATION_EMAIL="email_delivery": {"delivery_method": "_3A_smtp", "smtp_settings": {"address": "smtp.example.com", "port": 25}}
REDMINE_CONFIGURATION_AUTOLOGIN="autologin_cookie_name": "cookiename","autologin_cookie_path":"/cookie/","autologin_cookie_secure":"true"
```
would produce:
```yaml
default:
  autologin_cookie_name: cookiename
  autologin_cookie_path: "/cookie/"
  autologin_cookie_secure: true
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.example.com
      port: 25
```
The advantage of this method is that it allows to customize *any* part of `configuration.yml` the same way.

It requires some trickery to handle special values such as symbols (e.g. `:smtp`) or boolean values, but this is just a matter of syntax.

**Pull request closed without merging**
