### PR TITLE
add git to be able to use the redmine repository config

### PR DESCRIPTION
**Pull request by firecyberice**
With this PR redmine can show git repositories.

### CODE REVIEW

**Comment by yosifkit** [comment]
Cool! Two comments:

- Shouldn't we also add some or all of the [other supported version control systems](https://www.redmine.org/projects/redmine/wiki/RedmineRepositories)?
- We should just install `git` since `git-core` is a ["transitional dummy package"](https://packages.debian.org/jessie/git-core).

**Comment by firecyberice** [comment]
Okay I'll change git-core to git.
I have not used other vcs yet so I do not know what is needed for them to work but I add the packages from the deb repos.

**Comment by firecyberice** [comment]
ping @yosifkit I have changed / added packages according to your comment :-)

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
