### PR TITLE
Add Dockerfiles for 3.1 and 3.2 releases

### PR DESCRIPTION
**Pull request by rbayliss**
Hello,
Redmine 3.1 and 3.2 are out now, and ready for release.  I've added folders and Dockerfiles for 3.1 and 3.2, as well as update the .travis.yml to test them.  I think the stackbrew script has to be updated as well, but I didn't touch that, since I'm not sure how it works.

### CODE REVIEW

**Comment by yosifkit** [comment]
Thanks! :+1: LGTM

**Comment by yosifkit** [comment]
```diff
diff --git a/3.0/Dockerfile b/3.1/Dockerfile
index f13a9a9..2bd0ade 100644
--- a/3.0/Dockerfile
+++ b/3.1/Dockerfile
@@ -26,8 +26,8 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 ENV RAILS_ENV production
 WORKDIR /usr/src/redmine
 
-ENV REDMINE_VERSION 3.0.7
-ENV REDMINE_DOWNLOAD_MD5 d37fbcb2f0300821cb14c80dfc87ca87
+ENV REDMINE_VERSION 3.1.3
+ENV REDMINE_DOWNLOAD_MD5 09b0bbcef859fef51022750a94db7579
 
 RUN curl -fSL "http://www.redmine.org/releases/redmine-${REDMINE_VERSION}.tar.gz" -o redmine.tar.gz \
        && echo "$REDMINE_DOWNLOAD_MD5 redmine.tar.gz" | md5sum -c - \

diff --git a/3.0/Dockerfile b/3.2/Dockerfile
index f13a9a9..4332a28 100644
--- a/3.0/Dockerfile
+++ b/3.2/Dockerfile
@@ -26,8 +26,8 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 ENV RAILS_ENV production
 WORKDIR /usr/src/redmine
 
-ENV REDMINE_VERSION 3.0.7
-ENV REDMINE_DOWNLOAD_MD5 d37fbcb2f0300821cb14c80dfc87ca87
+ENV REDMINE_VERSION 3.2.0
+ENV REDMINE_DOWNLOAD_MD5 b1050c3a0e6effd5a704ef5003d9df06
 
 RUN curl -fSL "http://www.redmine.org/releases/redmine-${REDMINE_VERSION}.tar.gz" -o redmine.tar.gz \
        && echo "$REDMINE_DOWNLOAD_MD5 redmine.tar.gz" | md5sum -c - \

diff --git a/3.0/passenger/Dockerfile b/3.2/Dockerfile
index aa8ff25..0e729dd 100644
--- a/3.0/passenger/Dockerfile
+++ b/3.2/Dockerfile
@@ -1,4 +1,4 @@
-FROM redmine:3.0
+FROM redmine:3.2
 
 ENV PASSENGER_VERSION 5.0.23
 RUN buildDeps=' \
```

**Comment by rbayliss** [comment]
Thanks for merging!  I'm a little ignorant of how the packaging system works - is there a way to use the newer versions through the official repository?  Using redmine:3-passenger seems to give the older version (3.07).

**Comment by yosifkit** [comment]
Not a problem. :smile:  The process goes like this: Once updates are merged to a repo we have to make a PR to [docker-library/official-images](https://github.com/docker-library/official-images) and update the `redmine` file in the `library/` directory (which is generated from the ouput of the `generate-stackbrew-library.sh` file in this repo).  Once merged there, we tell the build server to build and push the image to Docker Hub.

**Pull request merged**
