### PR TITLE
Migrate plugins on startup of redmine

### PR DESCRIPTION
**Pull request by HaMster21**
Redmine has a rake task to iterate all plugins and perform migration steps. The reference can be found [here](https://www.redmine.org/projects/redmine/wiki/Plugins).

This will make it easier to integrate Plugins in the docker container. The user only has to mount a host folder with all the required plugins to /usr/src/redmine/plugins. With this rake task in place, all steps for making the plugins available are taken, though there may still be dependencies for the plugin that have to be installed first. In order to automate dependency installation, it might be a good idea to expect a bash script with the same name as the plugin that can takes care of the dependencies.

### CODE REVIEW

**Comment by HaMster21** [comment]
The Travis build failed due to an error during apt install in the 3.0 image build.

One additional question: is the entrypoint script automatically replicated to all images? If not, I will adapt all the files, not just the top-level one :wink:

**Comment by HaMster21** [comment]
ping @tianon @yosifkit

**Comment by yosifkit** [comment]
Yeah, the file gets copied when we run [update.sh](https://github.com/docker-library/redmine/blob/82efd8f4c09afcc9910a62752488e79df1dc0829/update.sh#L26).

Should this also be turned off (or maybe on) by a flag like the `db:migrate` is just a [few lines above](https://github.com/docker-library/redmine/blob/82efd8f4c09afcc9910a62752488e79df1dc0829/docker-entrypoint.sh#L64)?

**Comment by yosifkit** [comment]
Will we need to keep adding more rake tasks like this to the entrypoint?  We want to try and keep it simple.

Right now a user can just run their rake task to update their plugins: `docker run -d --name some-redmine --link some-postgres:postgres -v ~/plugins:/usr/src/redmine/plugins redmine rake redmine:plugins:migrate`; though both this and your addition will be dependent upon whether or not the `redmine` user in the container has access to write to the mounted directory.

**Comment by HaMster21** [comment]
I was getting issues when I tried to run plugins inside the container because the redmine docs say that you need to restart redmine in oder to activate the plugins. That's why I thought the startup script would be the place to go, redmine is started right after that.

I was evaluating redmine for our company and tried to package it with a compose script, [this one](https://gist.github.com/HaMster21/1bcff4aa24fc0596ecdc). Compose supports adding only a single `command` option for a container as far as I know. So I need to migrate all plugin stuff at container startup.

I agree on the flag to turn plugin migration on.

**Comment by yosifkit** [comment]
Yes, compose only allows a single command, but that could be something more complex like:
```yaml
command: [ 'sh', '-c', 'rake redmine:plugins:migrate && /docker-entrypoint.sh passenger start']
# ie, docker run ... redmine sh -c '....'
```
That should allow it to work right now for you, while we look to see if this is the only new command and flag or will this "open the flood gates" for more flags and rake tasks that other users would require.

**Comment by HaMster21** [comment]
Mh, I guess this also fixes my problem :smile:

So it's up to you whether to merge or not. I was also thinking about managing dependencies for the redmine plugins inside a container, and came to the conclusion that this is requiring me to build my own image.

**Comment by sealemar** [comment]
I was gonna suggest that change in a separate PR, but then I saw this one.

@yosifkit, do you suggest to run something like

```
command: [ 'sh', '-c', 'rake redmine:plugins:migrate && exec /docker-entrypoint.sh passenger start']
```

The first time someone wants to init Redmine and migrate existing plugins? I guess that is more of a question of priority -- what should we run first

1. `gosu redmine rake db:migrate` or 
2. `gosu redmine rake redmine:plugins:migrate RAILS_ENV=production`

In my version of `docker-entrypoint.sh` I run the `db:migrate` first and then (depending on the env variable as suggested by @HaMster21) I run `gosu redmine rake redmine:plugins:migrate RAILS_ENV=production`.

Note that the order is reversed if we do that https://github.com/docker-library/redmine/pull/10#issuecomment-179992501 (the version suggested by @yosifkit)

**Comment by sealemar** [comment]
Now as I've been thinking more about the `command` approach, I doubt it'll work. The thing is that the environment along with the `./config/database.yml` file is initialized in `/docker-entrypoint.sh`.

The `database.yml` file will only exist if a container has been stopped, meaning that `db:migrate` step has already been done, which answers the question about what migrate step to run first. However, if the container has been stopped, then it can only be started back, it can not take `command` parameter at this step.

If my logic is correct, the `command` approach will never work. In case if that is true, would you consider merging this PR provided the author adds the same information to other Dockerfiles?

**Comment by yosifkit** [comment]
The entrypoint does allow `rake` tasks to trigger the yaml creation, so modifying my previous suggestion would be:
```yaml
command: [ 'sh', '-c', '/docker-entrypoint.sh rake redmine:plugins:migrate && exec /docker-entrypoint.sh passenger start']
# ie, docker run ... redmine sh -c '/docker-entrypoint.sh rake redmine:plugins:migrate && exec /docker-entrypoint.sh passenger start'
```

**Comment by sloncho** [comment]
+1
I understand the concern of adding yet more flags, but many things in redmine are done trough plugins.  They are essential part of the ecosystem.

**Comment by kervel** [comment]
+1
maybe one could have the script only run redmine:plugins:migrate if the /usr/src/redmine/plugins directory contains at least one subdirectory.

**Comment by imaia** [comment]
+1 I like this PR very much. Would solve a few of my problems.

**Comment by imaia** [comment]
By the way, I'm not sure where to place the code below:

`command: [ 'sh', '-c', '/docker-entrypoint.sh rake redmine:plugins:migrate && exec /docker-entrypoint.sh passenger start']`

I'm having a hard time running migrate.

**Comment by yosifkit** [comment]
@imaia, that would be the syntax for a docker-compose.yml file.  On a docker run it should be something like `docker run -d --name redmine redmine sh -c '/docker-entrypoint.sh rake redmine:plugins:migrate && exec /docker-entrypoint.sh passenger start'`

**Comment by abcfy2** [comment]
+1 for this feature. Need redmine:plugins:migrate at startup.

**Comment by imaia** [comment]
Thanks, @yosifkit

**Comment by stucki** [comment]
This is ready to be merged, isn't it? Please let me know if any help is needed to proceed with this...

**Comment by yosifkit** [comment]
While my hacky CMD does work, it is probably more correct to do it this way since it will do database migrations before the plugin migrations.

**Pull request merged**
