### PR TITLE
create and use db adapter specific Gemfile.lock files to fix issue #74

### PR DESCRIPTION
**Pull request by NetworkEng**
Reference issue #74 
- Update Dockerfile to create adapter specific `Gemfile.lock.${adapter}` file.
- Update `docker-entrypoint.sh` to copy adapter specific file to Gemfile.lock

### CODE REVIEW

**Comment by NetworkEng** [comment]
Looking at the travis-ci jobs, I'm fairly certain the failures have nothing to do with this pull request. 3 failed and one passed job.  Someone who knows, please have a look?

Failed:
https://travis-ci.org/docker-library/redmine/jobs/253025763
https://travis-ci.org/docker-library/redmine/jobs/253025764
https://travis-ci.org/docker-library/redmine/jobs/253025765

Succeeded:
https://travis-ci.org/docker-library/redmine/jobs/253025766

All I added to the Dockerfile(s) was a cp command.  I'm pretty sure that was not the cause of the timeouts, causing a failed image creation.

**Comment by yosifkit** [comment]
Thanks @NetworkEng!

I added some more commits to make it work if they supply their own database.yml (or somehow the `Gemfile.lock` is missing).

**Comment by NetworkEng** [comment]
Thanks @yosifkit. Looks like the Travis CI build has failed for some reason.

**Comment by tianon** [comment]
The `redmine-basics` test has been extra flakey lately. :disappointed:

**Comment by tianon** [comment]
image

**Comment by NetworkEng** [comment]
Awesome! Thank you @tianon and @yosifkit !

**Pull request merged**
