### PR TITLE
Add same arches as ruby, Gosu & tini bump

### PR DESCRIPTION
**Pull request by yosifkit**
```diff
diff --git a/dev/fd/63 b/dev/fd/62
--- a/dev/fd/63
+++ b/dev/fd/62
@@ -1,11 +1,12 @@
-# this file is generated via https://github.com/docker-library/redmine/blob/083fd3c293a01cf19bcb3c24a05db31f6a6b05bb/generate-stackbrew-library.sh
+# this file is generated via https://github.com/docker-library/redmine/blob/10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9/generate-stackbrew-library.sh
 
 Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
              Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
 GitRepo: https://github.com/docker-library/redmine.git
 
 Tags: 3.4.2, 3.4, 3, latest
-GitCommit: bcaee7ff541b6ff01b7593e44444b3d561f67472
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
+GitCommit: 10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9
 Directory: 3.4
 
 Tags: 3.4.2-passenger, 3.4-passenger, 3-passenger, passenger
@@ -13,7 +14,8 @@ GitCommit: ded105e314a3b60130573e300931b149daf8fd8c
 Directory: 3.4/passenger
 
 Tags: 3.3.4, 3.3
-GitCommit: bcaee7ff541b6ff01b7593e44444b3d561f67472
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
+GitCommit: 10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9
 Directory: 3.3
 
 Tags: 3.3.4-passenger, 3.3-passenger
@@ -21,7 +23,8 @@ GitCommit: ded105e314a3b60130573e300931b149daf8fd8c
 Directory: 3.3/passenger
 
 Tags: 3.2.7, 3.2
-GitCommit: bcaee7ff541b6ff01b7593e44444b3d561f67472
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
+GitCommit: 10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9
 Directory: 3.2
 
 Tags: 3.2.7-passenger, 3.2-passenger
@@ -29,7 +32,8 @@ GitCommit: ded105e314a3b60130573e300931b149daf8fd8c
 Directory: 3.2/passenger
 
 Tags: 3.1.7, 3.1
-GitCommit: bcaee7ff541b6ff01b7593e44444b3d561f67472
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
+GitCommit: 10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9
 Directory: 3.1
 
 Tags: 3.1.7-passenger, 3.1-passenger
```

Replaces, closes #86.

### CODE REVIEW

**Comment by yosifkit** [comment]
Specifically leaving out architectures for passenger since they do not provide binaries for anything other than amd64.  Here is an example that can be used to build a passenger image yourself:

```Dockerfile
FROM redmine:3.4

RUN set -ex; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		libpcrecpp0 \
		libcurl3 \
		libssl1.0.0 \
		zlib1g \
	; \
	rm -rf /var/lib/apt/lists/*

ENV PASSENGER_VERSION 5.1.7

RUN buildDeps=' \
		make \
	' \
	&& set -x \
	&& apt-get update && apt-get install -y --no-install-recommends $buildDeps && rm -rf /var/lib/apt/lists/* \
	&& gem install passenger --version "$PASSENGER_VERSION" \
	&& apt-get purge -y --auto-remove $buildDeps

# pre-download the PassengerAgent and the NGINX engine
# this will build the agent since it does not exist anything but amd64
# https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.1.7/
RUN set -ex; \
	if [ "$(dpkg --print-architecture)" != 'amd64' ]; then \
		buildDeps='g++ gcc libcurl4-openssl-dev libpcre3-dev libssl-dev make zlib1g-dev'; \
		apt-get update; \
		apt-get install -y --no-install-recommends $buildDeps; \
		rm -rf /var/lib/apt/lists/*; \
		passenger-config compile-agent; \
		passenger-config compile-nginx-engine; \
		apt-get purge -y --auto-remove $buildDeps; \
	else \
		passenger-config install-agent; \
		passenger-config download-nginx-engine; \
	fi

CMD ["passenger", "start"]
```

**Comment by tianon** [comment]
Oh wait, `tini` doesn't support some of these architectures yet (see https://github.com/krallin/tini/pull/98).

**Comment by yosifkit** [comment]
Rather than writing code to get the list of supported arches from tini, I think we can wait a bit for tini to release a version that has them all.

**Comment by longquan7** [comment]
@tianon @yosifkit I have a problem that I want more images to support arm64, and I try to build different image on arm64 when I was build successed, I submit Issues or PR to contributor. but some questions have been unanswered. I don't konw how to do, There are other ways to add that images when it can be support arm64?

**Comment by tianon** [comment]
@longquan7 we don't plan to _force_ any maintainer to support non-amd64 arches -- the most we'll do is encourage and help

**Comment by longquan7** [comment]
@tianon OK,thanks. I'm also going to look for some images If they can support it for arm64.

**Comment by longquan7** [comment]
@tianon When can we add it to https://hub.docker.com/u/arm64v8/ ?

**Comment by tianon** [comment]
https://hub.docker.com/r/arm64v8/redmine/ :wink:

**Pull request merged**
