### PR TITLE
Add redmine 3.3 alpine favor

### PR DESCRIPTION
**Pull request by abcfy2**
Add redmine `3.3` and `3.3-passenger` alpine favor.

Key modifications:
1. based on `ruby:2.3-alpine` image.
2. bump `tini` and `gksu` to the latest version.
2. delete `~/.{gem,bundle}` after bundle install, this can save about 10MB size.
3. Add a variable `RUBYGEM_MIRROR` for mirroring `https://rubygems.org`

TODO: rewrite `docker-entrypoint.sh` to use `/bin/sh` as she-bang, to delete the `bash` dependence.

### CODE REVIEW

**Comment by J0WI** [comment]
Would you like to integrate this into `update.sh`?

**Comment by abcfy2** [comment]
If I have time, I will try to do.

**Comment by tianon** [comment]
As-is, this is not likely to be accepted.

We would prefer not to mess around with Alpine + Passenger (it's not clear whether the Passenger folks even support Alpine, but regardless it's an extra variable we're not comfortable with right now).

Additionally, `gosu` should be replaced with `su-exec` pulled from `apk` (and `tini` could be as well).

Additional behavior (like `RUBYGEM_MIRROR`) should be proposed separately so it can be discussed separately.

If there are size improvements to be had in the current image, we'd love to have those (so they ought to be separated out too).

This also _must_ be integrated with the existing `update.sh` for maintainability (and IMO it's way easier to develop/iterate on, especially across more than one Redmine version if this is done).

I'm also happy to take over and get Redmine + Alpine working and integrated (but with the caveat that it won't be a very high priority, especially since we don't have many users asking for it).

**Comment by J0WI** [comment]
I continued in #149, but it does not yet build successfully. Any help is welcome.

**Pull request closed without merging**
